blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
#    path('', views.PostListArticles.as_view(), name='blog'),
    path('articls/<int:page>/', views.PostListArticles.as_view(), name='blog_articls'),
    path('products/<int:page>/', views.PostListProducts.as_view(), name='blog_products'),
    path('edit_page/', views.PostEditPageView.as_view(), name='blog_edit_page'),
    path('edit/<int:pk>/', views.PostEditView.as_view(), name='blog_edit'),
    path('create/', views.PostCreateView.as_view(), name='blog_create_articles'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='blog_delete'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path('like/<slug:slug>', views.LikeViewClass.LikeView, name='like_post'),
]

site_for_bots/urls.py
from django.contrib import admin
from django.urls import path, include

#for ckeditor
from django.conf import settings
from django.conf.urls.static import static
#for ckeditor

urlpatterns = [
    path('admin/', admin.site.urls, name = 'admin_page'),
    path('', include('main.urls'), name = 'root'),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('social/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #for ckeditor

# для перевода
from django.conf.urls.i18n import i18n_patterns
urlpatterns += i18n_patterns(
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('social/', include('allauth.urls')),
)

blog/models.py
from django.db import models
from django.conf import settings
#from django.contrib.auth.models import User

#for ckeditor
#from ckeditor.fields import RichTextUploadingField
from ckeditor_uploader.fields import RichTextUploadingField
#for ckeditor

# For likes model
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
# For likes model

class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
    related_name='likes',
    on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

class Dislike(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
    related_name='dislikes',
    on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

class Post(models.Model):
    STATUS = (
        (0,"Draft"),
        (1,"Publish")
    )

    NEWS = (
        (0,"Articles"),
        (1,"Product"),
        (2,"HOME")
    )

    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete= models.CASCADE, blank=True, null=True)
    updated_on = models.DateTimeField(auto_now= True)
    content = RichTextUploadingField(blank=True, null=True, verbose_name='Контент', external_plugin_resources=[('youtube','/static/ckeditor/youtube/','plugin.js',)],)
    #content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    news = models.IntegerField(choices=NEWS, default=0)
    image_articles = models.ImageField(blank=True, null=True)
    #likes = models.ManyToManyField(User, related_name='blog_like')
    
    dislikes = GenericRelation(Dislike)
    likes = GenericRelation(Like)

    @property
    def total_likes(self):
        return self.likes.count()

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

class Comments(models.Model):
    post = models.ForeignKey(Post, on_delete= models.CASCADE, verbose_name='Пост', related_name='comments_post', blank=True, null=True)
    # Через поле 'author' можно попасть в 'User', а дальше в 'profile'
    # В ШОКЕ !!!!
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Автор', blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    content = models.TextField(verbose_name='Комментарий')
    status = models.BooleanField(verbose_name='Visible', default='True')

    likes = GenericRelation(Like)
    dislikes = GenericRelation(Dislike)

blog/forms.py
from .models import Post, Comments
from django.forms import ModelForm, TextInput, Textarea


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ["title", "slug", "content", "status", "news", "image_articles"]

        widgets = {
            "title": TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите название'}),

            "slug": TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите url статьи'}),
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comments
        fields = ('content',)

        widgets = {
            "content": Textarea(attrs={
            'class': 'form-control text-light',
            'placeholder': 'Вводи',
            'style': 'background-color: #302e3dc9; border-color: rgba(126, 136, 136, 0.651);',
            })
        }

blog/views.py
from django.views import generic
from .models import Post, Comments, Dislike, Like
from .forms import PostForm, CommentForm
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin #for Login access
from django.views.generic.edit import FormMixin
from django.http import HttpResponseRedirect
from .likes import add_like, remove_like, is_fan, get_fans
"""
class PostListArticles(generic.ListView):
    #queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'blog/articles.html'
    #context_object_name = 'list_articles'

    def get_queryset(self):
        queryset = Post.objects.all()
        queryset0 = queryset.filter(news=0,status=1).order_by('-created_on')
        return queryset0
"""

from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger


class PostListArticles(generic.ListView):
    model = Post
    template_name = "blog/articles.html"
    paginate_by = 20
    
    def get_context_data(self, **kwargs):
        context = super(PostListArticles, self).get_context_data(**kwargs) 
        list_exam = Post.objects.all()
        paginator = Paginator(list_exam, self.paginate_by)

        page = self.request.GET.get('page')

        try:
            file_exams = paginator.page(page)
        except PageNotAnInteger:
            file_exams = paginator.page(1)
        except EmptyPage:
            file_exams = paginator.page(paginator.num_pages)
            
        context['list_exams'] = file_exams
        return context

    def get_queryset(self):
        queryset = Post.objects.all()
        queryset0 = queryset.filter(news=0,status=1).order_by('-created_on')
        return queryset0


class PostListProducts(generic.ListView):
    #queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'blog/products.html'
    model = Post
    paginate_by = 20
    
    def get_context_data(self, **kwargs):
        context = super(PostListProducts, self).get_context_data(**kwargs) 
        list_exam = Post.objects.all()
        paginator = Paginator(list_exam, self.paginate_by)

        page = self.request.GET.get('page')

        try:
            file_exams = paginator.page(page)
        except PageNotAnInteger:
            file_exams = paginator.page(1)
        except EmptyPage:
            file_exams = paginator.page(paginator.num_pages)
            
        context['list_exams'] = file_exams
        return context

    def get_queryset(self):
        queryset = Post.objects.all()
        queryset0 = queryset.filter(news=1,status=1).order_by('-created_on')
        return queryset0


class PostDetail(FormMixin, generic.DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    form_class = CommentForm
    #success_url = reverse_lazy('post_detail')

    def get_success_url(self,**kwargs):
        return reverse_lazy('post_detail',kwargs={'slug': self.get_object().slug})

    def post(self,request,*args,**kwargs):
        form = self.get_form()
        if form.is_valid:
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.post = self.get_object()
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_context_data(self,**kwargs):
        kwargs['list_articles'] = Post.objects.all().order_by('-id')
        kwargs["liked"] = 'lol'
        return super().get_context_data(**kwargs)

class LikeViewClass():
    @classmethod
    def LikeView(cls,request,slug):
        namePOST = ['comment_id_like','post_id_dislike','comment_id_dislike','post_id_like']
        nameMODEL = {'post': Post, 'comment': Comments}
        nameMODEL0 = {'like': Like, 'dislike': Dislike}
        for i in namePOST:
            if request.POST.get(i):
                model = i.split('_')[0]
                model0 = i.split('_')[2]
                for nameI in nameMODEL:
                    if model == nameI:
                        obj0 = get_object_or_404(nameMODEL[model], id=request.POST.get(i))
                for nameII in nameMODEL0:
                    if model0 == nameII:
                        if is_fan(obj0, request.user, Like) == False and is_fan(obj0, request.user, Dislike) == False:
                            add_like(obj0, request.user, nameMODEL0[model0])

                        elif is_fan(obj0, request.user, Like) == True and is_fan(obj0, request.user, Dislike) == False:
                            if model0 == 'dislike':
                                remove_like(obj0, request.user, Like)
                                add_like(obj0, request.user, Dislike)
                            if model0 == 'like':

                                remove_like(obj0, request.user, Like)

                        elif is_fan(obj0, request.user, Like) == False and is_fan(obj0, request.user, Dislike) == True:
                            if model0 == 'like':
                                remove_like(obj0, request.user, Dislike)
                                add_like(obj0, request.user, Like)
                            if model0 == 'dislike':
                                remove_like(obj0, request.user, Dislike)


        return HttpResponseRedirect(reverse('post_detail', args=[str(slug)]))



class PostEditPageView(LoginRequiredMixin, generic.ListView):
    queryset = Post.objects.all()
    template_name = 'blog/edit_page.html'
    context_object_name = 'list_articles'

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_superuser and not self.request.user.is_staff:
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

class PostCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'blog/create.html'
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('blog_edit_page')

    def get_context_data(self,**kwargs):
        kwargs['list_articles'] = Post.objects.all().order_by('-id')
        return super().get_context_data(**kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if not self.request.user.is_superuser and not self.request.user.is_staff:
            return self.handle_no_permission()
        return kwargs

    # Чтобы сохранить статью под данным пользователем 
    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)

class PostEditView(LoginRequiredMixin, generic.UpdateView):
    model = Post
    template_name = 'blog/edit.html'
    form_class = PostForm
    success_url = reverse_lazy('blog_edit_page')

    # Чтобы редактировать только свои статьи
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if self.request.user != kwargs['instance'].author:
            return self.handle_no_permission()
        if not self.request.user.is_superuser and not self.request.user.is_staff:
            return self.handle_no_permission()
        return kwargs

class PostDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Post
    success_url = reverse_lazy('blog_edit_page')

    # Чтобы удалять только свои статьи
    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.request.user != self.object.author:
            return self.handle_no_permission()
        if not self.request.user.is_superuser and not self.request.user.is_staff:
            return self.handle_no_permission()
        self.object.delete()
        return redirect('blog_edit_page')



"""
def delete(request,pk):
    get_articles = Post.objects.get(pk=pk)
    get_articles.delete()
    return redirect('blog_edit_page')
"""


"""
def edit_page(request):
    context = {
        'list_articles': Post.objects.all().order_by('-id')
    }
    return render(request, 'blog/edit_page.html', context)
"""
"""
def edit(request, pk):
    get_articles = Post.objects.get(pk=pk)

    if request.method == 'POST':
        form = PostForm(request.POST,instance=get_articles)
        if form.is_valid():
            form.save()
            return redirect('blog_edit_page')

    context = {
        'get_articles': get_articles,
        'form': PostForm(instance=get_articles) #Подстановка данных в форму
    }
    return render(request,'blog/edit.html', context)
"""
"""
def create(request):
    error = ''
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog')
        else:
            error = 'Форма была говной'

    form = PostForm()
    context = {
        'form': form,
        'error': error
    }
    return render(request, 'blog/create.html', context)
"""

blog/templates/blog/articles.html
{% extends "blog/base.html" %}

{% block paginated %}
  {% if is_paginated %}
  <ul class="pagination justify-content-center">
  {% if page_obj.has_previous %}
      <li style="margin-right: 2ch;">
          <span><a href="{% url 'blog_articls' page_obj.previous_page_number %}">Previous</a></span>
      </li>
  {% endif %}
      <li>
          <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
      </li>
  {% if page_obj.has_next %}
      <li style="margin-left: 2ch;">
          <span><a href="{% url 'blog_articls' page_obj.next_page_number %}">Next</a></span>
      </li>
  {% endif %}
  </ul>
  {% endif %}
{% endblock paginated %}

blog/templates/blog/base.html
{% extends "main/base.html" %}
{% load static i18n %}
{% block title %}
{{ title }}
{% endblock %}

{% block content %}
 <style>
  a { 
    text-decoration: none; /* Отменяем подчеркивание у ссылки */
    color: rgb(38, 180, 38);
  } 
  a:hover {
    color: rgb(48, 206, 193);
  }
 </style>
      <div class="mt-4 col-md-2">

      </div>
      <div class="mt-4 col-md-7">
        <div class="card-title text-light" style="background-color: #302e3dc9;">
          <p class="text-center">{% block paginated %}{% endblock paginated %}</p>
        </div>

        {% for post in post_list %}
        <div class="card mb-4" style="background-color: #302e3dc9;">
          <div class="row card-body text-light">

            {% if post.image_articles %}
            <div class="col-xs-6 col-sm-3">
              <img src="/media/{{ post.image_articles }}" class="img-fluid rounded" width="220" height="220">
            </div>
            {% endif %}

            <div class="col-xs-6 col-sm-9">
              <h2 class="card-title">{{ post.title }}</h2>
              <!--<p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on }} </p>-->
              <a class="card-text text-muted" href="{% url 'profile_view' post.author.profile.slug %}">{{ post.author }} | {{ post.created_on }}</a>
              <p class="card-text">{{ post.content|striptags|slice:":200" }}</p>
              <a href="{% url 'post_detail' post.slug  %}" class="btn btn-secondary">{% trans 'Читать дальше' %} &rarr;</a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
      {% block sidebar %}
      {# {% include 'blog/sidebar.html' %} #}
      {% endblock sidebar %}
{%endblock%}

blog/templates/blog/create.html
{% extends 'main/base.html' %}
{% load static i18n %}
{% block title %}
Write
{% endblock %}
To write an article
{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container">
          <div class="row">
            <h1 class="mt-4 text-center text-light">Написать статью</h1>
            <div class="col-md-auto">
              {{ form.media }}
              {{ form.title }}
              {{ form.slug }}
              {{ form.content }}
              {{ form.image_articles }}

              {{ form.author }}
              {{ form.status }}
              {{ form.news }}
            </div>
            <button type="submit" class="btn btn-primary mt-4">Создать</button>
            <span>{{ error }}</span>
          </div>
        </div>
    </form>
{% endblock %}

blog/templates/blog/edit.html
{% extends 'main/base.html' %}
{% load static i18n %}
{% block title %}
{% trans 'Редактировать' %}
{% endblock %}


{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container">
          <h1 class="mt-4">{% trans 'Редактировать статью' %}</h1>
          <div class="row">
            <div class="col-md-auto">
              {{ form.media }}
              {{ form.title }}
              {{ form.slug }}
              {{ form.content }}
              

              {{ form.author }}
              {{ form.status }}
              {{ form.news }}

              <div><p>{{ form.image_articles }}</p></div>
            </div>
            <button type="submit" class="btn btn-primary mt-4">{% trans 'Обновить' %}</button>
            <span>{{ error }}</span>
          </div>
        </div>

    </form>
{% endblock %}

blog/templates/blog/edit_page.html
{% extends 'main/base.html' %}
{% load static i18n %}
{% block title %}
{% trans 'Панель редактирования' %}
{% endblock %}

{% block content %}
<div class="container mt-3">
  <div class="row card-body" style="background-color: #f2f1f8d0;">
    <a class="btn btn-primary btn-lg btn-block" href="{% url 'blog_create_articles' %}">{% trans 'Создать статью' %}</a>
    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">{% trans 'Заголовок' %}</th>
            <th scope="col">{% trans 'Дата' %}</th>
            <th scope="col">{% trans 'Автор' %}</th>
            <th scope="col">{% trans 'Где' %}</th>
            <th scope="col">{% trans 'Статус' %}</th>
            <th scope="col">######</th>
            <th scope="col">######</th>
          </tr>
        </thead>
        <tbody>
        {% for i in list_articles %}
          <tr>
            <th>{{ i.id }}</th>
            <td>{{ i.title }}</td>
            <td>{{ i.created_on }}</td>
            <td>{{ i.author }}</td>
            {% if i.news == 0 %}
            <td>Articles</td>
            {% elif i.news == 1 %}
            <td>Product</td>
            {% else %}
            <td>HOME</td>
            {% endif %}
            {% if i.status == 0 %}
            <td>{% trans 'Не опубликовано' %}</td>
            {% else %}
            <td>{% trans 'Опубликовано' %}</td>
            {% endif %}
            <td>
              <a href="{% url 'blog_edit' i.id %}" class="btn btn-outline-success btn-sm" role="button">{% trans 'Редактировать' %}</a><td>
              <form id="delete_form" action="{% url 'blog_delete' i.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-danger btn-sm">{% trans 'Удалить' %}</button>
              </form>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
  </div>
</div>

{% endblock %}

blog/templates/blog/index.html
{% extends "main/base.html" %}
      
 {% block content %}

    <header class="masthead" >
            <div class="overlay"></div>
            <div class="container">
              <div class="row">
                <div class=" col-md-8 col-md-10 mx-auto">
                  <div class="site-heading">
                </div>
                    </div>
                  </div>
                </div>
            </div>
              </header>
        
            <div class="container">
                <div class="row">
      
              <!-- Blog Entries Column -->
              <div class="col-md-8 mt-3 left">
                    {% for post in post_list %}
                <div class="card mb-4" >
                  <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>

                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                  </div>
                 
                </div>
                {% endfor %}
            </div>
                {% block sidebar %}
                {% include 'blog/sidebar.html' %}
                {% endblock sidebar %}
            </div>
        </div>
{%endblock%}

blog/templates/blog/post_detail.html
{% extends 'main/base.html' %} 
{% load static %}
{% load static i18n %}

{% block head_css %}
<link rel="stylesheet" href="{% static '/css/like.css' %}" type="text/css">
{% endblock %}

{% block content_in_root_body %}
<style>
  a { 
    text-decoration: none; /* Отменяем подчеркивание у ссылки */
  } 
 </style>
<div class="container text-light">
  <div class="row">
    <div class="col-10 card mb-4 mt-3 left top" style="background-color: #302e3dc9;">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <a class="text-muted card-text" href="{% url 'profile_view' post.author.profile.slug %}">{{ post.author }} | {{ post.created_on }}</a>
        <p class="card-text ">{{ object.content | safe }}</p>

        {% if user.is_authenticated %}
        <div class="row">
          <div class="col-9">

          </div>
          <div class="col">
            <!--Like-->
            <form action="{% url 'like_post' object.slug %}" method="POST">
              {% csrf_token %}
              <label>
                <input type="submit" name="post_id_like" value="{{ object.id }}">
                <svg viewbox=0,0,500,500 width="50px" height="50px">
                 <circle class="circle" cx="250" cy="250" r="210" fill="#fff" stroke="#000" stroke-width="8"/>
                 <text x="250" y="250">🔥</text>
               </svg>
               {{ object.likes.count }}
               </label>
            </form>
          </div>
          <div class="col">
            <!--Dislike-->
            <form action="{% url 'like_post' object.slug %}" method="POST">
            {% csrf_token %}
              <label>
                <input type="submit" name="post_id_dislike" value="{{ object.id }}">
                <svg viewbox=0,0,500,500 width="50px" height="50px">
                  <circle class="circle" cx="250" cy="250" r="210" fill="#fff" stroke="#000" stroke-width="8"/>
                  <text x="250" y="250">💤</text>
                </svg>
                {{ object.dislikes.count }}
              </label>
            </form>
          </div>
        </div>
          <hr>
        {% endif %}

        <p>{% trans 'Комментарии' %} ({{ object.comments_post.all.count }})</p>
        {% for item in object.comments_post.all %}
        <div class="card mb-2" style="background-color: #2e2f3dc9; border-color: rgba(126, 136, 136, 0.651);">
          <div class="row card-body" id="comments-list">
            <div class="col-1">
              <a href="{% url 'profile_view' item.author.profile.slug %}"><img src="/media/{{ item.author.profile.avatar }}" class="rounded-circle z-depth-0" alt="avatar image" height="60" width="60"></a>
            </div>
            <div class="col-10">
              {# Через поле 'author' можно попасть в 'User', а дальше в 'profile'   В ШОКЕ !!!! #}
              <a class="text-muted" href="{% url 'profile_view' item.author.profile.slug %}">{{ item.author }} | {{ item.created_on }}</a>
              <p>{{ item.content }}</p>
            </div>
            {% if user.is_authenticated %}
            <div class="col-1">
                <table>
                  <tr>
                      <td>
                        <!--Like-->
                        <form action="{% url 'like_post' object.slug %}" method="POST">
                            {% csrf_token %}      
                          <label> 
                            <input type="submit" name="comment_id_like" value="{{ item.id }}">                 
                            <svg viewbox=0,0,500,500 width="40px" height="40px">
                              <circle class="circle" cx="250" cy="250" r="210" fill="#fff" stroke="#000" stroke-width="8"/>
                              <text x="250" y="250">🔥</text>
                            </svg>
                          </label>
                        </form>
                      </td>
                      <!--👍 👎 💔 💗 💙 💚 💛 💜 💤 💥 💩 -->
                      <td>{{ item.likes.count }}</td>
                    </tr>
                  <tr>
                    <td>
                      <!--Dislike-->
                      <form action="{% url 'like_post' object.slug %}" method="POST">
                        {% csrf_token %}      
                        <label>             
                        <input type="submit" name="comment_id_dislike" value="{{ item.id }}">                  
                          <svg viewbox=0,0,500,500 width="40px" height="40px">
                            <circle class="circle" cx="250" cy="250" r="210" fill="#fff" stroke="#000" stroke-width="8"/>
                            <text x="250" y="250">💤</text>
                          </svg>
                        </label>
                      </form>
                    </td>
                      <td>{{ item.dislikes.count }}</td>
                  </tr>
              </table>
            </div>
            {% endif %}
              

            </div>
            </div>
          {% endfor %}
          {% if user.is_authenticated %}
          <p>{% trans 'Комментарий:' %}</p>
          <form id="add_form" action="" method="POST">
            {{ form.content }}
            {% csrf_token %}
            <button form="add_form" id="send-comment" type="submit" class="btn btn-primary btn-lg btn-sm btn-block">{% trans 'Оставить' %}</button>
          </form>
          {% endif %}
      </div>
    </div>
    {% block sidebar %} {# {% include 'blog/sidebar.html' %} #} {% endblock sidebar %}


  </div>
</div>

{% block js %}
<script>
</script>
{% endblock js %}

{% endblock content_in_root_body %}

blog/templates/blog/products.html
{% extends "blog/base.html" %}

{% block paginated %}
  {% if is_paginated %}
  <ul class="pagination justify-content-center">
  {% if page_obj.has_previous %}
      <li style="margin-right: 2ch;">
          <span><a href="{% url 'blog_products' page_obj.previous_page_number %}">Previous</a></span>
      </li>
  {% endif %}
      <li>
          <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
      </li>
  {% if page_obj.has_next %}
      <li style="margin-left: 2ch;">
          <span><a href="{% url 'blog_products' page_obj.next_page_number %}">Next</a></span>
      </li>
  {% endif %}
  </ul>
  {% endif %}
{% endblock paginated %}

blog/templates/blog/sidebar.html
{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }
       
</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
        <h5 class="card-header">About Us</h5>
    <div class="card-body">
        <p class="card-text"> This awesome blog is made on the top of our Favourite full stack Framework 'Django', follow up the tutorial to learn how we made it..!</p>
        <a href="#"
           class="btn btn-danger">Know more!</a>
    </div>
</div>
</div>

{% endblock sidebar %}